name: NSE Pipeline

on:
  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install httpx

      - name: Print UTC Time
        run: |
          echo "UTC Time:"; date -u
          echo "IST Time:"; TZ="Asia/Kolkata" date

      - name: Run NSE Pipeline
        env:
          WORKER_URL:   ${{ secrets.WORKER_URL }}
          WORKER_TOKEN: ${{ secrets.WORKER_TOKEN }}
        run: python pipeline_nse.py
